import type { Context } from '@deepseek-ai/cordis'
import type { ToolCallView, ToolResultView } from '@deepseek-ai/dsh-tools'
import { defineTool } from '@deepseek-ai/dsh-tools'
import { StripeClient, StripeError, type StripeClientOptions } from './client.js'

export { StripeClient, StripeError }
export type { StripeAccountInfo, StripeClientOptions, StripeCustomerInfo, StripeInvoiceInfo, StripeListResult, StripePaymentIntentInfo, StripePriceInfo, StripeProductInfo, StripeSubscriptionInfo } from './client.js'
export const name = 'dsh-tool-stripe'
export const inject = ['tools']
export interface StripePluginConfig extends StripeClientOptions {}

function text(value: string) { return [{ type: 'text' as const, text: value }] }
function unavailable(reason: string) { return { found: false, reason } }
function safeFailure(error: unknown): { found: false; reason: string } { if (error instanceof StripeError && (error.status === 429 || error.status >= 500)) throw error; return { found: false, reason: error instanceof Error ? error.message : 'Stripe request failed.' } }
function pageText(value: { hasMore?: boolean; nextCursor?: string }) { return 'hasMore=' + Boolean(value.hasMore) + (value.nextCursor ? ' nextCursor=' + value.nextCursor : '') }
function readKind(title: string): ToolCallView { return { card: 'generic', title, kind: 'read' } }

export function createTools(client: StripeClient) {
  return [
    defineTool({
      name: 'stripe_auth_test', description: 'Verify a Stripe API key and return safe account fields without exposing the key.', parameters: {},
      output: { schema: { type: 'object', additionalProperties: false, properties: { ok: { type: 'boolean' }, reason: { type: 'string' }, id: { type: 'string' }, country: { type: 'string' }, defaultCurrency: { type: 'string' }, businessName: { type: 'string' }, chargesEnabled: { type: 'boolean' }, payoutsEnabled: { type: 'boolean' } } } as const, render: (_args, value) => value.ok ? text('Stripe account ' + value.id + ' country=' + value.country) : text('Stripe auth failed: ' + value.reason) },
      presentCall(): ToolCallView { return readKind('Verify Stripe API key') },
      async execute(_args, exec) { if (!client.hasKey()) return { ok: false, reason: 'Stripe API key is not configured.' }; try { return { ok: true, ...await client.authTest(exec.signal) } } catch (error) { if (error instanceof StripeError && (error.status === 401 || error.status === 403)) return { ok: false, reason: error.message }; throw error } },
    }),
    defineTool({
      name: 'stripe_list_customers', description: 'List Stripe customers with bounded cursor pagination and safe identity fields.', parameters: { email: { type: 'string', description: 'Optional exact email filter.' }, limit: { type: 'integer', description: 'Results, 1-100.' }, startingAfter: { type: 'string', description: 'Stripe cursor from the previous page.' }, endingBefore: { type: 'string', description: 'Reverse cursor from the previous page.' } },
      output: { schema: { type: 'object', additionalProperties: false, properties: { found: { type: 'boolean' }, reason: { type: 'string' }, items: { type: 'array', items: { type: 'object', additionalProperties: false, properties: { id: { type: 'string' }, email: { type: 'string' }, name: { type: 'string' }, description: { type: 'string' }, created: { type: 'integer' }, currency: { type: 'string' }, delinquent: { type: 'boolean' } } } }, hasMore: { type: 'boolean' }, nextCursor: { type: 'string' } } } as const, render: (_args, value) => value.found ? text((value.items ?? []).map(item => item.id + ' ' + item.email + ' ' + item.name).join('\n') + '\n' + pageText(value)) : text(value.reason ?? 'Stripe is not configured.') },
      presentCall(args): ToolCallView { return readKind('Stripe customers' + (args.email ? ': ' + args.email : '')) },
      async execute(args, exec) { if (!client.hasKey()) return unavailable('Stripe API key is not configured.'); try { return { found: true, ...await client.listCustomers({ email: args.email, limit: args.limit, startingAfter: args.startingAfter, endingBefore: args.endingBefore, signal: exec.signal }) } } catch (error) { return safeFailure(error) } },
    }),
    defineTool({
      name: 'stripe_list_products', description: 'List Stripe products with bounded cursor pagination. Raw metadata, payment links, and prices are not returned.', parameters: { active: { type: 'boolean', description: 'Optional active filter.' }, type: { type: 'string', description: 'Optional product type filter.' }, limit: { type: 'integer', description: 'Results, 1-100.' }, startingAfter: { type: 'string', description: 'Stripe cursor from the previous page.' }, endingBefore: { type: 'string', description: 'Reverse cursor from the previous page.' } },
      output: { schema: { type: 'object', additionalProperties: false, properties: { found: { type: 'boolean' }, reason: { type: 'string' }, items: { type: 'array', items: { type: 'object', additionalProperties: false, properties: { id: { type: 'string' }, name: { type: 'string' }, active: { type: 'boolean' }, description: { type: 'string' }, defaultPriceId: { type: 'string' }, created: { type: 'integer' } } } }, hasMore: { type: 'boolean' }, nextCursor: { type: 'string' } } } as const, render: (_args, value) => value.found ? text((value.items ?? []).map(item => item.id + ' ' + item.name + (item.active ? ' active' : ' inactive')).join('\n') + '\n' + pageText(value)) : text(value.reason ?? 'Stripe is not configured.') },
      presentCall(): ToolCallView { return readKind('Stripe products') },
      async execute(args, exec) { if (!client.hasKey()) return unavailable('Stripe API key is not configured.'); try { return { found: true, ...await client.listProducts({ active: args.active, type: args.type, limit: args.limit, startingAfter: args.startingAfter, endingBefore: args.endingBefore, signal: exec.signal }) } } catch (error) { return safeFailure(error) } },
    }),
    defineTool({
      name: 'stripe_list_subscriptions', description: 'List Stripe subscriptions with status/customer filters and safe billing-period fields.', parameters: { customerId: { type: 'string', description: 'Optional customer id.' }, status: { type: 'string', description: 'Optional subscription status.' }, priceId: { type: 'string', description: 'Optional price id filter.' }, limit: { type: 'integer', description: 'Results, 1-100.' }, startingAfter: { type: 'string', description: 'Stripe cursor from the previous page.' }, endingBefore: { type: 'string', description: 'Reverse cursor from the previous page.' } },
      output: { schema: { type: 'object', additionalProperties: false, properties: { found: { type: 'boolean' }, reason: { type: 'string' }, items: { type: 'array', items: { type: 'object', additionalProperties: false, properties: { id: { type: 'string' }, status: { type: 'string' }, customerId: { type: 'string' }, currentPeriodStart: { type: 'integer' }, currentPeriodEnd: { type: 'integer' }, cancelAtPeriodEnd: { type: 'boolean' }, collectionMethod: { type: 'string' }, currency: { type: 'string' } } } }, hasMore: { type: 'boolean' }, nextCursor: { type: 'string' } } } as const, render: (_args, value) => value.found ? text((value.items ?? []).map(item => item.id + ' ' + item.status + ' customer=' + item.customerId).join('\n') + '\n' + pageText(value)) : text(value.reason ?? 'Stripe is not configured.') },
      presentCall(): ToolCallView { return readKind('Stripe subscriptions') },
      async execute(args, exec) { if (!client.hasKey()) return unavailable('Stripe API key is not configured.'); try { return { found: true, ...await client.listSubscriptions({ customerId: args.customerId, status: args.status, priceId: args.priceId, limit: args.limit, startingAfter: args.startingAfter, endingBefore: args.endingBefore, signal: exec.signal }) } } catch (error) { return safeFailure(error) } },
    }),
    defineTool({
      name: 'stripe_list_invoices', description: 'List Stripe invoices with customer/status filters and safe amount fields. Invoice URLs and PDF links are not returned.', parameters: { customerId: { type: 'string', description: 'Optional customer id.' }, status: { type: 'string', description: 'Optional invoice status.' }, collectionMethod: { type: 'string', description: 'Optional collection method.' }, limit: { type: 'integer', description: 'Results, 1-100.' }, startingAfter: { type: 'string', description: 'Stripe cursor from the previous page.' }, endingBefore: { type: 'string', description: 'Reverse cursor from the previous page.' } },
      output: { schema: { type: 'object', additionalProperties: false, properties: { found: { type: 'boolean' }, reason: { type: 'string' }, items: { type: 'array', items: { type: 'object', additionalProperties: false, properties: { id: { type: 'string' }, number: { type: 'string' }, status: { type: 'string' }, customerId: { type: 'string' }, amountDue: { type: 'integer' }, amountPaid: { type: 'integer' }, currency: { type: 'string' }, created: { type: 'integer' }, dueDate: { type: 'integer' } } } }, hasMore: { type: 'boolean' }, nextCursor: { type: 'string' } } } as const, render: (_args, value) => value.found ? text((value.items ?? []).map(item => item.id + ' ' + item.status + ' due=' + item.amountDue + ' paid=' + item.amountPaid).join('\n') + '\n' + pageText(value)) : text(value.reason ?? 'Stripe is not configured.') },
      presentCall(): ToolCallView { return readKind('Stripe invoices') },
      async execute(args, exec) { if (!client.hasKey()) return unavailable('Stripe API key is not configured.'); try { return { found: true, ...await client.listInvoices({ customerId: args.customerId, status: args.status, collectionMethod: args.collectionMethod, limit: args.limit, startingAfter: args.startingAfter, endingBefore: args.endingBefore, signal: exec.signal }) } } catch (error) { return safeFailure(error) } },
    }),
    defineTool({
      name: 'stripe_list_payment_intents', description: 'List Stripe PaymentIntents with safe status, amount, currency, and customer fields. Card and client-secret fields are never returned.', parameters: { customerId: { type: 'string', description: 'Optional customer id.' }, limit: { type: 'integer', description: 'Results, 1-100.' }, startingAfter: { type: 'string', description: 'Stripe cursor from the previous page.' }, endingBefore: { type: 'string', description: 'Reverse cursor from the previous page.' } },
      output: { schema: { type: 'object', additionalProperties: false, properties: { found: { type: 'boolean' }, reason: { type: 'string' }, items: { type: 'array', items: { type: 'object', additionalProperties: false, properties: { id: { type: 'string' }, status: { type: 'string' }, amount: { type: 'integer' }, currency: { type: 'string' }, customerId: { type: 'string' }, created: { type: 'integer' }, description: { type: 'string' } } } }, hasMore: { type: 'boolean' }, nextCursor: { type: 'string' } } } as const, render: (_args, value) => value.found ? text((value.items ?? []).map(item => item.id + ' ' + item.status + ' amount=' + item.amount + ' ' + item.currency).join('\n') + '\n' + pageText(value)) : text(value.reason ?? 'Stripe is not configured.') },
      presentCall(): ToolCallView { return readKind('Stripe payment intents') },
      async execute(args, exec) { if (!client.hasKey()) return unavailable('Stripe API key is not configured.'); try { return { found: true, ...await client.listPaymentIntents({ customerId: args.customerId, limit: args.limit, startingAfter: args.startingAfter, endingBefore: args.endingBefore, signal: exec.signal }) } } catch (error) { return safeFailure(error) } },
    }),
    defineTool({
      name: 'stripe_list_prices', description: 'List Stripe Prices with product, active, currency, and recurring filters. Raw metadata, tiers, transforms, and payment fields are not returned.', parameters: { productId: { type: 'string', description: 'Optional product ID filter.' }, active: { type: 'boolean', description: 'Optional active filter.' }, type: { type: 'string', description: 'Optional price type: one_time or recurring.' }, currency: { type: 'string', description: 'Optional three-letter currency filter.' }, limit: { type: 'integer', description: 'Results, 1-100.' }, startingAfter: { type: 'string', description: 'Stripe cursor from the previous page.' }, endingBefore: { type: 'string', description: 'Reverse cursor from the previous page.' } },
      output: { schema: { type: 'object', additionalProperties: false, properties: { found: { type: 'boolean' }, reason: { type: 'string' }, items: { type: 'array', items: { type: 'object', additionalProperties: false, properties: { id: { type: 'string' }, active: { type: 'boolean' }, currency: { type: 'string' }, unitAmount: { type: 'integer' }, unitAmountDecimal: { type: 'string' }, type: { type: 'string' }, productId: { type: 'string' }, nickname: { type: 'string' }, recurringInterval: { type: 'string' }, recurringIntervalCount: { type: 'integer' }, billingScheme: { type: 'string' }, taxBehavior: { type: 'string' }, created: { type: 'integer' } } } }, hasMore: { type: 'boolean' }, nextCursor: { type: 'string' } } } as const, render: (_args, value) => value.found ? text((value.items ?? []).map(item => item.id + ' ' + item.currency + ' amount=' + item.unitAmount + (item.recurringInterval ? ' every ' + item.recurringInterval : '') + (item.active ? ' active' : ' inactive')).join('\n') + '\n' + pageText(value)) : text(value.reason ?? 'Stripe is not configured.') },
      presentCall(): ToolCallView { return readKind('Stripe prices') },
      async execute(args, exec) { if (!client.hasKey()) return unavailable('Stripe API key is not configured.'); try { return { found: true, ...await client.listPrices({ productId: args.productId, active: args.active, type: args.type, currency: args.currency, limit: args.limit, startingAfter: args.startingAfter, endingBefore: args.endingBefore, signal: exec.signal }) } } catch (error) { return safeFailure(error) } },
    }),
  ]
}

export function apply(ctx: Context, config: StripePluginConfig = {}): void { const client = new StripeClient(config); for (const tool of createTools(client)) ctx.tools.register(tool) }
